version: 2.1

commands:
  alpine_checkout:
    description: install dependencies for CCI's `checkout`
    steps:
      - run: apk add --no-cache ca-certificates git openssh-client
      - run: update-ca-certificates
      - checkout

  install:
    steps:
      - restore_cache:
          key: v1-{{ arch }}-{{ checksum "yarn.lock" }}
      - alpine_checkout
      - run: yarn --pure-lockfile --cache-folder /tmp/.yarn_cache
      - save_cache:
          key: v1-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - /tmp/.yarn_cache
      - npm_login

  npm_login:
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPMJS_TOKEN}" >> ~/.npmrc

executors:
  node:
    docker:
      - image: node:lts-alpine
    working_directory: /percolate/blend

jobs:
  core:
    executor: node
    steps:
      - install
      - run: npx lerna run build
      - run: npx kona verify
      - run: npx kona ts
      - run: npx kona lint
      - run: npx kona commit validate
      - run: npx kona test --coverage
      - run: npx kona coverage
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              echo "Skipping - only runs on master"
              exit 0
            fi
            yarn lerna:publish --yes
      - store_test_results:
          path: tmp/reports

  press:
    executor: node
    steps:
      - alpine_checkout
      - run: apk add --no-cache docker
      - npm_login
      - run: yarn global add @percolate/press
      - setup_remote_docker
      - run:
          command: |
            docker build \
              --build-arg NPMJS_TOKEN \
              --build-arg VERSION=$(press --version) \
              --tag blend/press .
          working_directory: containers/press
      - run: press push blend/press --repo="percolate/blend/press" --semver=$(press --version)

workflows:
  version: 2
  blend:
    jobs:
      - core
      - press:
          requires:
            - core
