version: 2

jobs:
  build:
    docker:
      - image: node:lts
    working_directory: /percolate/blend
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          key: v2-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v2-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - tmp/.yarn_cache
            - node_modules
      - run: npx lerna run build
      - run: npx kona verify
      - run: npx kona ts
      - run: npx kona lint
      - run: npx kona commit validate
      - run: npx kona test --coverage
      - run: npx kona coverage
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
                echo "Skipping: only runs on master"
                exit 0
            fi

            echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" >> ~/.npmrc
            yarn lerna:publish --yes
      - store_test_results:
          path: tmp/reports
