version: 2

jobs:
  build:
    docker:
      - image: node:lts
    working_directory: /percolate/blend
    steps:
      - checkout
      - add_ssh_keys

      - restore_cache:
          key: v2-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile --cache-folder /tmp/.yarn_cache

      - save_cache:
          key: v2-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - /tmp/.yarn_cache
            - node_modules

      - run: yarn run lint
      - run: yarn run prettier
      - run: npx lerna run test -- --colors
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
                echo "Skipping: only runs on master"
                exit 0
            fi

            echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" >> ~/.npmrc
            bin/publish --yes
